name: Swift Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: xcodebuild -scheme swift-tts-Package -destination "platform=iOS Simulator,name=iPhone 14 Pro"

    - name: Run test
      run: xcodebuild test -scheme swift-tts-Package -destination "platform=iOS Simulator,name=iPhone 14 Pro"
